### ISSUE TITLE
Ant gardens issues 

### ISSUE THREAD

**Issue by Mechalopa** [N1nn1/spawn#3]
Ant gardens biome has no translation.

I also think it needs to be registered to `minecraft:is_overworld`, `minecraft:stronghold_biased_to` biome tags or other appropriate `forge:*`/`c:*` namespace biome tag.

**Comment by N1nn1** [comment]
Fixed the translation issue in 1.0.3, Tags will be likely fixed in another bugfix update if it occurs, if it doesn't it will be for next version

**Comment by eviltek2099** [comment]
Playing with Seed: [-7187558798595102158] with default setting of uncharted-expeditions and Ant Gardens not found anywhere. Traveled over 10000 in all directions and compass says not found!
Forge version: 1.0.4.2
https://www.curseforge.com/minecraft/modpacks/uncharted-expeditions
